name: Deploy Portfolio to AWS

on:
  push:
    branches:
      - main # Tự động chạy khi push code vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            # 1. Định nghĩa đường dẫn tuyệt đối
            TARGET_DIR="/home/huan1/portfolio"
            
            # 2. Nếu thư mục chưa tồn tại, thực hiện clone mới
            if [ ! -d "$TARGET_DIR" ]; then
              echo "Thư mục không tồn tại. Đang clone mới..."
              git clone https://github.com/Du73/portfolio.git "$TARGET_DIR"
            fi
            
            # 3. Vào thư mục và cập nhật code
            cd "$TARGET_DIR"
            git pull origin main
            
            # 4. Build và chạy Docker containers
            sudo docker compose up -d --build