name: Deploy Portfolio to AWS

on:
  push:
    branches:
      - main # Tự động chạy khi push code vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            TARGET_DIR="/home/huan1/portfolio"
            
            # Nếu thư mục tồn tại nhưng không phải git (lỗi build cũ), xóa sạch
            if [ -d "$TARGET_DIR" ] && [ ! -d "$TARGET_DIR/.git" ]; then
              sudo rm -rf "$TARGET_DIR"
            fi

            # Nếu chưa có thư mục, tiến hành clone mới
            if [ ! -d "$TARGET_DIR" ]; then
              git clone https://github.com/Du73/portfolio.git "$TARGET_DIR"
            fi
            
            # Di chuyển vào thư mục và cập nhật code
            cd "$TARGET_DIR"
            git pull origin main
            
            # Chạy Docker (Dùng sudo nếu chưa logout/login lại)
            sudo docker compose up -d --build